### ISSUE TITLE
Occasionally the facility location is outside the polygon

### ISSUE THREAD

**Issue by mmuller** [instedd/planwise#101]
Found in version 6ec5b5c

Actual result:
Occasionally the facility location is outside the polygon

Expected result:
The facility location should be inside the polygon

Screenshot:
![screen shot 2016-07-29 at 2 45 22 pm](https://cloud.githubusercontent.com/assets/518152/17258044/78590d34-559b-11e6-83b8-a942e52b6d54.png)
![screen shot 2016-07-29 at 2 47 18 pm](https://cloud.githubusercontent.com/assets/518152/17258045/785d6910-559b-11e6-90f0-740d9c52c32c.png)

**Comment by ggiraldez** [comment]
This is because the location of the facility does not fall inside the routing network graph and the isochrones are calculated using *only* the network graph. One quick fix is including a segment from the original facility position to the closest routing node into the solution for calculating the isochrone. Care must be taken to discard facilities too far away from the routing network.

**Comment by mmuller** [comment]
On occasions some areas are excluded from the polygon but when selecting another value as accepted travel time those areas are unexpectedly connected.
If there is no route to connect two points when changing the accepted travel time the connection between those points should not be affected.

**Comment by mmuller** [comment]
Some Facility locations are outside the polygon in version v0.4.0-32-g8fa416d

![screen shot 2016-08-09 at 5 24 45 pm](https://cloud.githubusercontent.com/assets/518152/17532490/2f44eebe-5e57-11e6-9ad4-99e9dfb24080.png)

**Comment by ggiraldez** [comment]
From Concern's feedback, Taylor:

>...and there were some dots (facilities) that were not surrounded by green, which I was also confused by.

Netta:

>Something else I saw happen a few times is in the picture below. There’s a facility right in the middle of an area that the tool says you can’t get to within the time frame. If the tool is right and you can’t actually access that facility, seeing something like this would make me question the reliability of the tool and the data because it “appears” wrong. So I think some way of explaining why this is happening would be useful.

**Comment by nditada** [comment]
Let's 
- [ ] have an internal (invisible for now) configuration for the acceptable distance of a facility from the closest segment in the road network.
- [ ] ignore the facilities that are further than that.
- [ ] color them in something like red and have a tooltip with: "This facility is too far from the closest road and it is not being evaluated for coverage."

**Comment by mmuller** [comment]
Ok in version v0.4.0-195-g1d88c2c
