### ISSUE TITLE
Compute unsatisfied demand raster layer

### ISSUE THREAD

**Issue by ggiraldez** [instedd/planwise#105]
- Start from the demographics layer
- Order the filtered facilities **by capacity in descending order**
- For each facilitiy, remove the capacity from the unsatisfied demand layer in the area covered by the facility's isochrone. The capacity used for each cell in the isochrone should be proportional to the unsatisfied demand on that cell (wrt. all the isochrone)

**Comment by mmuller** [comment]
Ok in version v0.4.0-151-gf78af9f
