### ISSUE TITLE
Split ways to improve granularity of the resulting catchment polygons

### ISSUE THREAD

**Issue by ggiraldez** [instedd/planwise#11]
Currently, `osm2pgrouting` only splits the OSM ways at interesection points. This means that if a splitted way is long enough to traverse the isochrone, it will not be included in the catchment polygon. For long segments this yields undesired results excluding roads that should be inside the polygon. To avoid that, either split the ways (given a distance granularity) or implement other means to split the problematic edge in the algorithm itself.

**Comment by nditada** [comment]
Just trying to have some fun late at night: it feels like determining the max length for an edge above which we have to split is an analog problem to the nyquist theorem, maybe that length should be half of  the isochrone resolution. e.g. if we precalculate isochrones at intervals of 15 minutes, shouldn't the max edge length be shorter than 7.5 minutes?

**Comment by mmuller** [comment]
In some cases if the acceptable travel time is 30 minutes some roads are excluded of the polygon but when changing the acceptable travel time those roads are inside the polygon. It can be reproduced with the following test data:

Facility location: Baragoi, Kenya.
Facility coordinates: 1.7851° N, 36.7873° E.

![screen shot 2016-07-26 at 2 38 55 pm](https://cloud.githubusercontent.com/assets/518152/17148873/2e6d943c-533f-11e6-8aa1-c531d4b455ed.png)
![screen shot 2016-07-26 at 2 39 11 pm](https://cloud.githubusercontent.com/assets/518152/17148872/2e6a92be-533f-11e6-8c5c-b8c4fc58d5dd.png)
![screen shot 2016-07-26 at 2 40 23 pm](https://cloud.githubusercontent.com/assets/518152/17148888/3e2e1ee6-533f-11e6-80c0-7af7171b8865.png)
![screen shot 2016-07-26 at 2 41 13 pm](https://cloud.githubusercontent.com/assets/518152/17148887/3e2a5d60-533f-11e6-90e5-aadf7bf74330.png)

**Comment by ggiraldez** [comment]
This was fixed by modifying `osm2pgrouting` in https://github.com/manastech/osm2pgrouting/pull/2

**Comment by mmuller** [comment]
Polygons are improved and roads are not being excluded in version v0.4.0-7-gcb5904c
