### ISSUE TITLE
Change markers to improve performance

### ISSUE THREAD

**Issue by spalladino** [instedd/planwise#113]
Transparent divs with CSS are quite expensive. Consider removing opacity, and using SVGs or images instead of DIVs.

**Comment by spalladino** [comment]
PR https://github.com/instedd/planwise/pull/107 changed markers from an SVG layer to div markers. Compare performance between both versions.

**Comment by spalladino** [comment]
The main performance issue was being caused by the layer definition being dependant on a function (popup-fn), which caused the layer to be considered different on every map move, and being fully redrawn.

**Comment by mmuller** [comment]
Ok in version v0.4.0-178-g80a5a8a
