### ISSUE TITLE
When some facilities are located on the water notify that there is no routing information about that facilities. 

### ISSUE THREAD

**Issue by mmuller** [instedd/planwise#114]
Found in version: v0.4.0-7-gcb5904c

Prerequisites:
A collection 'Foo' has facilities located in the water.

Reproduce steps:
Import the collection 'Foo'.
Create a Project  for that collection.
Go to the 'Transport Means' tab.
Select a value for the accepted travel time.
Observe the place markers and the coverage displayed in the map.

Obtained:
The isochrones cannot be calculated properly.

Expected:
Ideally we should not have pins in the water.
If we have place markers in the water we should ignore them when calculating the isochrones.

![screen shot 2016-08-02 at 3 54 47 pm](https://cloud.githubusercontent.com/assets/518152/17341103/7a08a898-58c9-11e6-9a4e-4322d0f56646.png)

**Comment by spalladino** [comment]
Shouldn't this issue be considered solved by #183?

**Comment by ggiraldez** [comment]
Yes, closing as fixed by #183.

**Comment by mmuller** [comment]
Ok in version v0.4.0-256-gb0f94f7
