### ISSUE TITLE
Map can reach an inconsistent state when changing regions in new project dialog

### ISSUE THREAD

**Issue by ggiraldez** [instedd/planwise#118]
This is due to an interaction between Leaflet and React. For example, selecting the Isiolo region and then changing to Kajiado. Since the target region is near the current viewport, Leaflet will try to pan-animate the map to move to Kajiado's center. This in turn triggers the on-position-changed handler which resets the map's center to the reported position. The map ends in an inconsistent state.

Event successions such as this can also lead to map "wiggling".

**Comment by mmuller** [comment]
![screen shot 2016-08-03 at 3 36 05 pm](https://cloud.githubusercontent.com/assets/518152/17377445/0c11a520-5990-11e6-8a87-39f90834335f.png)

**Comment by mmuller** [comment]
Ok in version v0.4.0-178-g80a5a8a
