### ISSUE TITLE
Address isolated components in the topology graph

### ISSUE THREAD

**Issue by ggiraldez** [instedd/planwise#12]
There are some instance in the OSM data where some ways are completely isolated from the road network (eg. a pedestrian pathway; see Lat -1.2595 Lon 36.8446). If a facility is located near one, the algorithm will choose a node in the isolated component for the origin of the isochrone and will yield an incorrect catchment area. There might be other places where there are disconnections due to human error when entering the map data as well.

Either remove the isolated components entirely or find a way to detect and correct these situations.

**Comment by mmuller** [comment]
For some facilities (eg. -1.61073, 39.02545) its polygon is displayed only when zooming in.

<img width="1232" alt="screen shot 2016-08-31 at 9 04 44 pm" src="https://cloud.githubusercontent.com/assets/518152/18150782/dac7e466-6fbf-11e6-8a48-7c0c41bc9191.png">
<img width="1301" alt="screen shot 2016-08-31 at 9 04 17 pm" src="https://cloud.githubusercontent.com/assets/518152/18150783/dac8856a-6fbf-11e6-9197-6a956679014c.png">
![Uploading Screen Shot 2016-08-31 at 9.03.40 PM.png…]()

**Comment by mmuller** [comment]
Ok in version 0.5.1-186-g0883e85
