### ISSUE TITLE
Support multi-tenancy

### ISSUE THREAD

**Issue by ggiraldez** [instedd/planwise#125]
This is an umbrella ticket for multi-tenancy support in Planwise. A rough specification follows:

## Data ownership

- Projects should be owned by a single user.
- By default, users will only see and have access to their own projects.
- The system can support multiple datasets, eg. multiple sets of facilities.
- Datasets should be owned by a single user.
- New datasets are created by importing a collection from Resourcemap
- (For now) Datasets cannot be changed/updated once imported
- Datasets have an identifying name, a "source" Resourcemap collection and field mapping information; this will allow automatically sync'ing the dataset from Resourcemap in the future
- Projects use one dataset, selected at project's creation time
- Datasets cannot be deleted if they are being referenced in one or more projects

## Project sharing

- Projects can be shared with other users via a "connect link"
- Once a user opens the "connect link" she will have access to the shared project and the project will appear in her projects list
- Projects can only be shared for read-only access; only the owner is able to alter the filters/scenarios
- A user can choose to unfollow a shared project which will remove it from her list
- The owner user can list users who have access to the project and revoke access individually
- Project sharing confers read access to the associated dataset in the context of the project only (ie. the receiving user cannot create a new project with the shared project dataset)

**Comment by nditada** [comment]
> (For now) Datasets cannot be changed/updated once imported
Not sure about that one. Why is that? If you also can't replace the dataset for a project, how do you have the facility list?

>The owner user can list users who have access to the project and revoke access 
That's a NTH, we can leave that in the backlog for the end of the project.

>Project sharing confers read access to the associated dataset in the context of the project only 
I'm indifferent to that. We can go either way, depending on what's easiest to implement (i.e. it's ok if you can use the shared facility list in another project, I see no problem).

**Comment by ggiraldez** [comment]
>> (For now) Datasets cannot be changed/updated once imported

> Not sure about that one. Why is that? If you also can't replace the dataset for a project, how do you have the facility list?

This is just to make the initial implementation simple, but can be added in the next release (or this one should time allow it). Since the dataset will keep the source collection from Resourcemap as well as the mappings, it will be possible to update the facility list by importing the same collection again.

>> Project sharing confers read access to the associated dataset in the context of the project only

> I'm indifferent to that. We can go either way, depending on what's easiest to implement (i.e. it's ok if you can use the shared facility list in another project, I see no problem).

I think it's simpler that way. Otherwise, as a dataset owner you lose control over it. Eg. you can't delete it because somebody else used it; if you update the facilities by re-importing you are changing somebody else's scenarios. I'm sure there are many other side effects or corner cases.

**Comment by ggiraldez** [comment]
Closed by #179. The project sharing parts are now in #155 and #156.

**Comment by mmuller** [comment]
Ok in version v0.4.0-253-g00446b8
