### ISSUE TITLE
Verify the sum of the regions' populations

### ISSUE THREAD

**Issue by spalladino** [instedd/planwise#128]
The sum of the precalculated population per region for all regions in Kenya is `47986498`, while the population for the Kenya region itself is `42066880`.

**Comment by spalladino** [comment]
After ab8d3aeca9c1afbb356e25fbf9436d6b5c8a1db3, the difference is reduced to 48035883 (sum) vs 48041323 (Kenya), just 5440 or 0.01% of error.

**Comment by mmuller** [comment]
Ok in Version: 0.5.1-186-g0883e85
