### ISSUE TITLE
Render facilities with color/symbol depending on the type

### ISSUE THREAD

**Issue by ggiraldez** [instedd/planwise#147]
From Concern feedback, Taylor:

>Maybe have different colored dots for the different types of centers so you can differentiate between the types of facilities on the map? (for example: hospitals = purple, dispensaries = red, etc.)

Stephen:

>Color/shape filtering for facility type? A hover key for what facility types mean/offer and perhaps identify facilities appropriate to certain issues/conditions? Building in a set of best practice parameters for a range of issues/conditions?

**Comment by spalladino** [comment]
As discussed with @jkicillof, draw all facilities from the same type on the same svg group, and draw the group with the least number of elements last, so a rare facility type is not hidden by a common one. Ensure the mix-blend-mode is multiply for the layers.

For creating a palette, pick the main color of each group from [Google material design](https://material.google.com/style/color.html#).

See https://github.com/instedd/planwise/pull/161

**Comment by mmuller** [comment]
Ok in version v0.4.0-160-gcb48a66
