### ISSUE TITLE
Review wording on filters screens

### ISSUE THREAD

**Issue by ggiraldez** [instedd/planwise#148]
From Concern feedback, Grace:

>When choosing facility types the text reads Select the facilities that are satisfying the demand you are analyzing. I had to read this a few times to understand what it was saying. How about: Select the type of facility to include in your analysis.

Also, from Katie:

>In the text on acceptable travel time we should ensure that people know this is round trip.

**Comment by nditada** [comment]
Let's go with: "Select the types of facility to include in your analysis. We will use those to calculate the existing coverage."

**Comment by mmuller** [comment]
Ok in version: v0.4.0-183-g9f0f086
