### ISSUE TITLE
Improve site navigation

### ISSUE THREAD

**Issue by ggiraldez** [instedd/planwise#150]
From Concern's feedback (Grace):

>I almost wish for a next button or an arrow to click once I’ve selected my facilities. I sort of got stuck and wasn’t sure what to do once I had selected the facilities. I think you click on “transport means”? But I’m not sure.

>There doesn’t seem to be an easy way to move between projects. I created a project, and then wanted to go back and look at a larger region and the only way I could find to get back to the “home page” was to delete the project I was working on. It’s possible there’s a way to do it but it may need to be more clear.

**Comment by fgasperij** [comment]
Several changes were decided to address these issues. First, to ease the navigation from the project page and the listing or home page:

- remove the underlining of the Project tab header when inside a specific project.
- add a Back button to the project page that will allow the user to navigate back to the projects listing.

Then, to aid the understanding of the project workflow:

- the first time a user creates a project it will be welcomed by a wizard mode of the Demographics, Facilities and Transport Means tabs that will include:
  - a Next and a Back button on the bottom of each tab to navigate to the right or left tab, giving an order to them.
  - the heading of each tab will transition from light gray (not visited), dark gray (currently visiting) and green (already visited).

**Comment by jkicillof** [comment]
https://projects.invisionapp.com/d/main#/console/2626537/184745402/preview

**Comment by ggiraldez** [comment]
This needs UX design.

**Comment by mmuller** [comment]
Ok in Version: 0.5.1-186-g0883e85
