### ISSUE TITLE
Project sharing

### ISSUE THREAD

**Issue by ggiraldez** [instedd/planwise#155]
- Allow users to share projects by generating and sharing a link
- Opening the link gives read access to the project to anyone
- List shared projects for a user
- Allow opening a shared project in read-only mode

See #125.

**Comment by spalladino** [comment]
@jkicillof we'd need advise on the design for the following:

- [ ] A _sharing_ section for a project (a new tab? a modal dialog?) that allows its owner to copy/reset a sharing link, optionally write a list of email recipients to automatically send that link to, and view the list of people who currently have access to that project.
- [ ] A read-only view of a project (same as the current but with disabled filters? a different one with all the read-only filtering information condensed into a single tab?)
- [ ] A way for a user to identify projects in the project list that were shared with her (ie she doesn't own, and can only see in read-only mode).

**Comment by jkicillof** [comment]
https://projects.invisionapp.com/d/main#/console/2626537/184956357/preview
https://projects.invisionapp.com/d/main#/console/2626537/184956356/preview

**Comment by mmuller** [comment]
Ok in version 0.5.1-95-g80c2660
