### ISSUE TITLE
Properly escape HTML entities in facilities popups

### ISSUE THREAD

**Issue by ggiraldez** [instedd/planwise#164]
In https://github.com/instedd/planwise/blob/280101d91a48a52ea90a51e97884ab83d22ff6e0/src/planwise/client/projects/views.cljs#L43 the string is used raw by Leaflet. This makes it possible to inject arbitrary JS code via the the site name/facility type from Resourcemap. It's a long shot and I'm giving it low importance because once we have multi-tenancy all the data is provided by a single user.

**Comment by mmuller** [comment]
Ok in version 0.5.1-130-gab8d3ae
