### ISSUE TITLE
Display alert in project view if dataset is importing

### ISSUE THREAD

**Issue by spalladino** [instedd/planwise#182]
When viewing a project whose dataset is in an importing state, display an alert banner notifying the user that some facilities may be missing isochrones, and data is still updating.

Query the server every X seconds to check if the import has finished to remove the banner.

**Comment by spalladino** [comment]
Also display an alert if the dataset was cancelled.

**Comment by mmuller** [comment]
Ok in version 0.5.1-130-gab8d3ae
