### ISSUE TITLE
Remember wizard state when the user navigates away from a project

### ISSUE THREAD

**Issue by ggiraldez** [instedd/planwise#190]
When the user creates a new project, the wizard mode is activated for it until she visits all the project tabs. If she navigates away from the project and there are still tabs to visit, the next time she opens the project she should be taken back to the spot where she left off.

**Comment by ggiraldez** [comment]
Current WIP is in the `feature/wizard-memento` branch.

**Comment by mmuller** [comment]
Ok in version 0.6.1-56-g6b11a0f
