### ISSUE TITLE
Do not import sites with unknown type

### ISSUE THREAD

**Issue by juanedi** [instedd/planwise#191]
If a resmap dataset includes site with an empty type field, we are currently creating a facility with no type. This doesn't seem right, since there is no way to visualise those facilities in the application.

We should probably ignore those sites and add a warning saying that they weren't imported because of not having a known type.

Also, consider adding a DB contraint to avoid having null references for the facility>type FK.

**Comment by mmuller** [comment]
Ok in version 0.5.1-130-gab8d3ae
