### ISSUE TITLE
Show project's dataset

### ISSUE THREAD

**Issue by ggiraldez** [instedd/planwise#194]
Somewhere in the UI we need to show the dataset selected for the project. Otherwise it's impossible to know past the "new project" dialog.

**Comment by ggiraldez** [comment]
There are two aspects to consider:

1. Should we show the dataset name in the project's card in the list?
2. In a project screen, should we show the dataset name

  a) prominently in the project header?
  b) in the sidebar when viewing the facilities tab?

Opinions @nditada @jkicillof ?

**Comment by nditada** [comment]
I would add it in the "Facilities" tab, I think that's where I would look for it.

**Comment by spalladino** [comment]
@jkicillof something like this would work?

![screen shot 2016-09-06 at 4 33 26 pm](https://cloud.githubusercontent.com/assets/429604/18287954/b28bcfb4-744f-11e6-89f9-a7e365235b55.png)

**Comment by mmuller** [comment]
In version 0.5.1-130-gab8d3ae the dataset name is correctly displayed in the "Facilities" tab.
The dataset name is not included in the project's card in the list.
