### ISSUE TITLE
Show that the import process was cancelled

### ISSUE THREAD

**Issue by ggiraldez** [instedd/planwise#195]
After cancelling an import process, there's no indication in the dataset that the import didn't complete because it was cancelled by the user.

Import result is being saved to the database though (as the `:result` key), just not shown in the UI.

**Comment by spalladino** [comment]
@jkicillof this is how datasets are being shown when:
- Import was successful
- Import was successful but there were warnings
- There was an error while importing
- The import process was cancelled

Any suggestions on how to improve it?

![screen shot 2016-09-05 at 9 46 03 am](https://cloud.githubusercontent.com/assets/429604/18248307/be173e8e-734d-11e6-8e6a-4e4498655633.png)

**Comment by mmuller** [comment]
Ok in version 0.5.1-95-g80c2660
