### ISSUE TITLE
Review population density scale and colors

### ISSUE THREAD

**Issue by ggiraldez** [instedd/planwise#199]
The legend control assumes that each pixel is 100m x 100m and uses the maximum value from the raster file to display the population density. From recent measurements, the pixel size for the Kenya raster file is about 92m x 92m and may vary from country to country, depending on the data from Worldpop.

See also #142 

Since we're now using a mostly linear scale, low density areas appear empty when rendering the map. We might want to adjust the scale and use a saturated logarithmic scale, as in http://sedac.ciesin.columbia.edu/downloads/maps/grump-v1/grump-v1-population-density/kendens.jpg 

To do that, we need to review the normalization process **and** the colors used in the Mapserver configuration file. See https://drive.google.com/open?id=10qTOKQHq96aIEJ2UE0iiJSgf5jmWBBZ8qAgH1JOfFHc

Discuss with @nditada, @jkicillof and @juanedi 

![kendens](https://cloud.githubusercontent.com/assets/733591/18150153/188e4e8e-6fbb-11e6-9501-84a8c6e23a80.jpg)

**Comment by nditada** [comment]
Let's make the scale look like this:
![](https://files.slack.com/files-pri/T02JWDRK4-F28Q5FDU4/screen_shot_2016-09-01_at_11.07.05.png)

**Comment by juanedi** [comment]
Note that the problem regarding the pixel area size is fixed in (currently pending) PR #202.

**Comment by mmuller** [comment]
Ok in version 0.5.1-130-gab8d3ae
