### ISSUE TITLE
Rasterize catchment areas for cross-processing with demographics

### ISSUE THREAD

**Issue by ggiraldez** [instedd/planwise#20]
Given the isochrone polygons for each facility, rasterize them for processing with the demographic raster layer and compute the satisfied population by the facility.

Use the raster data from http://www.worldpop.org.uk/ and [GDAL](http://gdal.org) for data manipulation.

**Comment by fgasperij** [comment]
816cce9ab55e3fe17003f3e847ca66904341fafe
