### ISSUE TITLE
Map's viewport does not fit the project's region on the 2nd time it is loaded

### ISSUE THREAD

**Issue by spalladino** [instedd/planwise#216]
Steps to reproduce:
- Load planwise home page
- Open a project in Nairobi (for example)
- The map's viewport correctly wraps around Nairobi (see 1st screenshot)
- Go back to the project's list
- Open another project (for example, in Kenya)
- Go back to the project's list
- Open the 1st Nairobi project once again

Expected: the map's viewport correctly fits Nairobi as in the 1st screenshot
Actual: it is centered on Nairobi, but on a too far zoom level (see 2nd screenshot)

Correct fit:
![screen shot 2016-09-09 at 3 01 21 pm](https://cloud.githubusercontent.com/assets/429604/18397430/94cd1162-769e-11e6-9a16-cfd8dbe9296a.png)

Incorrect fit:
![screen shot 2016-09-09 at 3 03 04 pm](https://cloud.githubusercontent.com/assets/429604/18397436/9add06f2-769e-11e6-99a1-bc02b6935259.png)

**Comment by mmuller** [comment]
Ok in Version: 0.5.1-186-g0883e85
