### ISSUE TITLE
Projects cannot be shared with people who currently has no Planwise account.

### ISSUE THREAD

**Issue by mmuller** [instedd/planwise#219]
Found in version: 0.5.1-95-g80c2660

Prerequisites:
The recipient 'foo@bar.com' is not a Planwise user.
There is a Project 'Foo'.

Reproduce steps:
Sign in as owner of Project 'Foo'.
Share 'Foo' with the recipient 'foo@bar.com'.
Open the access email, create an account and confirm it.
Sign in.

Obtained:
The user is redirected to the Projects listing but the Project 'Foo' is not included in the list.
The new user cannot access the Project 'Foo'.

Additional information:
The email include the following text: _"If you do not have a PlanWise account, you will be prompted to create one when you access the link."_

**Comment by spalladino** [comment]
Is the new account `foo@bar.com`, or are you using a different email address?

**Comment by mmuller** [comment]
An access email is sent to 'foo@bar.com'.
I am creating an account in Planwise for the email address 'foo@bar.com'.

**Comment by spalladino** [comment]
The complete workflow for a completely new user is:
1- Receive share link via email
2- Open it and land in GUISSO login
3- Create an account
4- GUISSO asks the user to click on the link sent on the confirmation email
5- User follows the confirmation email
6- GUISSO tells the user that her account is now confirmed, and redirects her back to login
7- User logs in, and is redirected to the shared project

In some cases, on step (7), the user is redirected back to Planwise's home page, and has no access to the shared project. Investigate the cause of this issue.

Nonetheless, by clicking again on the link from step (1), the access is effectively granted.
