### ISSUE TITLE
Sharing URL sent by email is invalid

### ISSUE THREAD

**Issue by ggiraldez** [instedd/planwise#255]
Generated URL for accessing a shared project as generated in email is invalid. Eg:

http://planwise.instedd.org/api/projects/48/share/projects/48/access/ee9cecbf-4484-41c8-9a89-53bb3339f6f4b

when it should read:

http://planwise.instedd.org/projects/48/access/ee9cecbf-4484-41c8-9a89-53bb3339f6f4b

**Comment by mmuller** [comment]
Ok in version 0.7.0-4-gaab2e67
