### ISSUE TITLE
Unable to use scripts/migrate

### ISSUE THREAD

**Issue by bcardiff** [instedd/planwise#367]
`lein migrate` which is used in `scripts/migrate` is no longer working
This is used in bootstrap-dev.sh

```
Starting (:duct/migrator)
    Exception in thread "main" clojure.lang.ExceptionInfo: Error on key :duct.database.sql/hikaricp when building system
```

**Comment by ggiraldez** [comment]
I suspect this is due to a missing `DATABASE_URL` environment variable. This should work inside the docker container though, but will fail on the host since the default for development is set in `dev.edn` which is only loaded when starting from the REPL.

**Comment by ggiraldez** [comment]
The command works inside the development and production Docker containers. When executing in the host, the `DATABASE_URL` must be defined in the environment.
