### ISSUE TITLE
Sidebar covered population stays as zero PlanWise v1 (Prod)

### ISSUE THREAD

**Issue by edjez** [instedd/planwise#382]
Does sidebar still get information about covered population (in 3rd tab where transport duration is chosen)? 
Now is always showing as zero even for projects that used to work fine (eg Kilifi (http://planwise.instedd.org/projects/58/transport) )

Note:
Suspecting a recent cleanup may have unsubscribed the event or missing a field in project-data but haven't brought up the environment to validate.

https://github.com/instedd/planwise/blob/80f46cf21b6f7905aa98a140f284d8d61115e62e/src/planwise/client/current_project/components/sidebar.cljs#L134

**Comment by edjez** [comment]
![image](https://user-images.githubusercontent.com/1182549/39683882-e36ba9fa-516c-11e8-8d49-080fdeb348d8.png)

**Comment by ggiraldez** [comment]
Fixed. We recently deployed a newly built container to support one additional country and that broke binary compatibility for the programs that calculate the demand. I patched the previous stable container (instedd/planwise:0.7.3) and deployed that instead.

**Comment by ggiraldez** [comment]
See #389
