### ISSUE TITLE
Add current capacity and demand information to providers endpoint

### ISSUE THREAD

**Issue by bcardiff** [instedd/planwise#479]
#current-bug: ~~it seems the "capacity workload" is not used currently in the popup~~ rename field to reflect correctly that it is demand and not capacity

Besides provider's location, id and name. The following fields should be generated: Capacity. Used capacity. Free capacity. Required capacity. Satisfied demand. Unsatisfied demand.
* add: Used capacity. Free capacity. Required capacity.

Popup information of suggestion should have: needed capacity to supply demand. and demand amount to satisfy.

The required capacity is discarding other potential providers that could be upgraded (ie: satisfy all the reachable demand).

**Comment by solsarratea** [comment]
Free capacity and required capacity might have decimals
