### ISSUE TITLE
Display providers on map

### ISSUE THREAD

**Issue by bcardiff** [instedd/planwise#482]
* that have saturated capacity as red (this sites are the candidates to have their capacity increased)
* that have no saturated capacity as blue (this are sites were no action is required since they have unused capacity)
* filtered sites on map as gray icon (this are the one that can be upgraded)

There would need to be an endpoint per scenario since this information is sensible to the scenario's change set.
The color should be updated is the capacity of a site is increased beyond of it's need.
It should include sites added in the change set.

**Comment by ggiraldez** [comment]
This was fixed by #491
