### ISSUE TITLE
Allow the user to filter facilities by type

### ISSUE THREAD

**Issue by ggiraldez** [instedd/planwise#5]
Given the facility type, the use should be able to choose the types of facilities that are shown in the map.

**Comment by nditada** [comment]
selection for "lower" level facility types should include "higher" level. e.g. "I want to see ONLY hospitals" or " I want to see all facilities, including dispensaries".

**Comment by ggiraldez** [comment]
Superseded by #24.

Not sure about whether selection for lower level should include higher levels. According to the mockup, different facility types should be individually selectable.
