### ISSUE TITLE
Map zoom starts at 1 for all scenarios

### ISSUE THREAD

**Issue by manumoreira** [instedd/planwise#517]
When creating a project at planwise.instedd.org the scenario maps start at zoom 1 (all the world) 
It should focus on the selected region.

**Comment by manumoreira** [comment]
I'm selecting Addis Ababa as region and using this provider list 
[mening.eth.txt](https://github.com/instedd/planwise/files/2540892/mening.eth.txt)

**Comment by manumoreira** [comment]
When selecting small ethiopian regions as Harari, Addis or Dire Dawa the zoom goes to 1 after every action in the scenario.

**Comment by ggiraldez** [comment]
This should be fixed in edbdc6e685d5fa6c8fe526ab503a55a372aea8d6
