### ISSUE TITLE
Suggestions for new provider are not working.

### ISSUE THREAD

**Issue by mmuller** [instedd/planwise#518]
Version 0.8.0

Preconditions:
There is a Project `P`.

Steps to reproduce:
Go to `P`.
Create a new scenario.
Open the browser's console.
Select `Get suggestions for improve existing provider`.

Obtained:
The message `computing best locations` is displayed.
Time out is thrown on the browser's console.

**Comment by ggiraldez** [comment]
With latest changes, the algorithm should be able to respond in time (usually between 10-15 seconds).
