### ISSUE TITLE
Uploading providers Fails

### ISSUE THREAD

**Issue by steesdale** [instedd/planwise#530]
I tried to upload a small provider set, the upload failed for walking times. 

<img width="1417" alt="screen shot 2019-02-26 at 8 50 17 am" src="https://user-images.githubusercontent.com/3987608/53399363-c5a6b480-39a3-11e9-9da8-f343c4b5c9e5.png">

**Comment by nditada** [comment]
Worked after retry. Maybe a connection issue?
