### ISSUE TITLE
When changing settings of a scenario the percentages and source demand do not update

### ISSUE THREAD

**Issue by juanboca** [instedd/planwise#548]
The selected Region is Kenya, but the displayed percentage and source demand are from the previous region (a smaller province).

![Screen Shot 2019-10-02 at 17 12 19](https://user-images.githubusercontent.com/488553/66169971-a26a7480-e618-11e9-98d8-b63280c9dead.png)

The only workaround for this is to reload the page.

**Comment by mmuller** [comment]
Working properly in version https://github.com/instedd/planwise/commit/0b59abec759f53acc6673524ecc217b15e3c11ac
