### ISSUE TITLE
The colours on facilities markers are not very clear

### ISSUE THREAD

**Issue by juanboca** [instedd/planwise#549]
When a facility is missing the required capacity by 1000 or by 1, the colour of the marker is red.
As soon as it meets the required capacity, and even if it goes over it by 1000, it turns blue.

The colour should indicate in a clearer range where the new capacity is related to the required capacity.

![image](https://user-images.githubusercontent.com/25181052/68057130-c8486f00-fcd3-11e9-93e6-3d9226a71e6e.png)

**Comment by juanboca** [comment]
Related commit: https://github.com/instedd/planwise/commit/818ba43f23bfa3dff87567b5fb7aa39017a81131

**Comment by mmuller** [comment]
Working properly in version https://github.com/instedd/planwise/commit/0b59abec759f53acc6673524ecc217b15e3c11ac
