### ISSUE TITLE
Coverage settings' scope

### ISSUE THREAD

**Issue by diegoliberman** [instedd/planwise#552]
Move the coverage setting from the providers, to the project.
-> This will allow to create projects without providers (now it can be done creating an empty provider).

This is the setting that needs to be moved:
![image](https://user-images.githubusercontent.com/25181052/68057256-22493480-fcd4-11e9-9574-a2c8b8f5f6f2.png)

**Comment by juanboca** [comment]
Fixed on https://github.com/instedd/planwise/commit/906601a729e4eda717e9a17843fc614133c3d1cf

**Comment by mmuller** [comment]
Working properly in version https://github.com/instedd/planwise/commit/0b59abec759f53acc6673524ecc217b15e3c11ac
