### ISSUE TITLE
Distance buffer

### ISSUE THREAD

**Issue by diegoliberman** [instedd/planwise#560]
Extend the range to more than 100km for the distance buffer algorithm.

### Prerequisites
- When creating the project, select a provider which **Coverage Algorthm** is "Distance Buffer".  Bear in mind that in the ticket #552, this setting will be moved to the project.
![image](https://user-images.githubusercontent.com/25181052/68057032-7bfd2f00-fcd3-11e9-9da5-0771053db47d.png)

### Summary
Add options beyond 100km in this field:
![image](https://user-images.githubusercontent.com/25181052/68056975-55d78f00-fcd3-11e9-9099-6b4289f7a331.png)

**Comment by mmuller** [comment]
Working properly in version https://github.com/instedd/planwise/commit/0b59abec759f53acc6673524ecc217b15e3c11ac
