### ISSUE TITLE
Create one provider in staging fails

### ISSUE THREAD

**Issue by ggiraldez** [instedd/planwise#562]
In latest staging builds, the operation to create a new provider by clicking on a geographic location fails. The given error in the JS console is:
```
TypeError: d is undefined main.js:2647:172
    eW https://planwise-stg.instedd.org/js/main.js:2647
    fire https://planwise-stg.instedd.org/assets/leaflet/leaflet.js:5
    _fireDOMEvent https://planwise-stg.instedd.org/assets/leaflet/leaflet.js:5
    _handleDOMEvent https://planwise-stg.instedd.org/assets/leaflet/leaflet.js:5
    r https://planwise-stg.instedd.org/assets/leaflet/leaflet.js:5
```

Most likely, there's a missing export for Leaflet in the `externs.js` file

**Comment by juanboca** [comment]
Fixed on https://github.com/instedd/planwise/commit/96b4142ac2d52453b875530dd408e81ecedff64d
