### ISSUE TITLE
Show total demand under geographic coverage

### ISSUE THREAD

**Issue by diegoliberman** [instedd/planwise#567]
- [x] Within the Facility Details box, add the reached demand gained with that facility. Let's name that "[Consumer unit] under geographic coverage" or "Reachable by X [Consumer unit]"
![image](https://user-images.githubusercontent.com/25181052/68882505-09864900-06ee-11ea-8402-12cda730851d.png)
- [x] In the left pane, add the total demand reached with the existing and proposed facilities. Let's name that "Total [Consumer unit] under geographic coverage"  or "Total [Consumer unit] with access to [providers]"
![image](https://user-images.githubusercontent.com/25181052/68882563-24f15400-06ee-11ea-8ee6-205f43bf9ef7.png)

**Comment by diegoliberman** [comment]
- [ ] Within the Facility Details box, add the covered demand  gained with that facility.
![image](https://user-images.githubusercontent.com/25181052/68882505-09864900-06ee-11ea-8402-12cda730851d.png)
- [ ] In the left pane, add the total covered demand reached with the suggested facilities.
![image](https://user-images.githubusercontent.com/25181052/68882563-24f15400-06ee-11ea-8ee6-205f43bf9ef7.png)

**Comment by mmuller** [comment]
Working properly in version 30469426
