### ISSUE TITLE
List of suggested facilities

### ISSUE THREAD

**Issue by diegoliberman** [instedd/planwise#568]
- Show a list of the facilities suggested by Planwise, to be able to quickly find and analyse each option (otherwise, the user has to select 1 by 1 in the map).
- The initial idea was to locate this list in a space within the left sidebar.  However, that space is used to show the providers that are actually created by the social planner.  Not sure if it’s OK to use that space for something else.
- This effort will require UX/UI guidelines.
![image](https://user-images.githubusercontent.com/25181052/68882702-77327500-06ee-11ea-9656-bd920704208d.png)

**Comment by diegoliberman** [comment]
@jkicillof please add to this ticket the UX/UI proposal, when you have it.

**Comment by jkicillof** [comment]
@diegoliberman We should replace de FAB icon with `+` and make it rotate on menu opening to become an `x`. When the user clicks on a suggested site she should see a pop up with actions settings.
https://projects.invisionapp.com/d/main#/console/13565845/296384143/preview
https://projects.invisionapp.com/d/main#/console/13565845/394090846/preview
https://projects.invisionapp.com/d/main#/console/13565845/394090845/preview
https://projects.invisionapp.com/d/main#/console/13565845/296384142/preview

**Comment by mmuller** [comment]
Working properly in version 30469426
