### ISSUE TITLE
Hide Demographic tab for the first release version.

### ISSUE THREAD

**Issue by mmuller** [instedd/planwise#57]
Currently (version 92a3c56) the demographic tab is displayed but there is no demographic data.

![screen shot 2016-07-22 at 10 44 04 am](https://cloud.githubusercontent.com/assets/518152/17058971/44055850-4ff9-11e6-9b84-03ba18cf25a3.png)

**Comment by ggiraldez** [comment]
We should hopefully close this as `wontfix` :)

**Comment by ggiraldez** [comment]
Closed by #42.

**Comment by mmuller** [comment]
Demographic tab is correctly hidden in version 7202d3e
