### ISSUE TITLE
When switching to "suggestions for improve existing provider" mode, the user can't switch back to normal mode

### ISSUE THREAD

**Issue by juanboca** [instedd/planwise#572]
Once the "get suggestions for improve existing provider", the suggestions are displayed and the only way to get out of this mode is to improve a provider or reload the page. 

The button does not transform into a "close" button as in the other two modes.

![Screen Shot 2020-01-29 at 15 27 29](https://user-images.githubusercontent.com/488553/73385477-fd9d3280-42ab-11ea-94a1-cb9f19329541.png)

**Comment by mmuller** [comment]
Working properly in version 30469426
