### ISSUE TITLE
When trying to create a Project without 'walking time' an error is thrown

### ISSUE THREAD

**Issue by mmuller** [instedd/planwise#575]
**Found in version:**
30469426

**Steps to reproduce:**
1. Make sure you have a template with Walking Distance as Coverage Algorithm.
1. Try to create a new project from a template.
1. Submit without changing anything.  (if you move the slider, walking time will be set to 1h and the error won't be reproduced)
1. The error should be raised.

**Obtained:**
The project is not created.
The following error is logged in the browsers's console:
`POST https://planwise-stg.instedd.org/api/projects2/299/start 400 (Bad Request)`

### Proposed solution
Validate that the options were entered depending on the selected coverage algorithm.

**Comment by ggiraldez** [comment]
This is because the "Ground Access" template only has default coverage options for "Driving time". If "Walking distance" is selected, the coverage options do not have a default value which later breaks the scenario computation.

**Comment by mmuller** [comment]
Projects without `walking time`can be created in version https://github.com/instedd/planwise/commit/ebe6ebcf397f585b51ffcced87a9a1a39dadefc1.

Take into account that a draft of the project is created. To start the project the walking time must have a value. 

@ggiraldez could you confirm if this is the expected behavior after your fix?

**Comment by ggiraldez** [comment]
Yes, that's what the fix does. It checks for the correct coverage parameters before allowing to start the project. But, it does not provide default values.
