### ISSUE TITLE
[Scenarios] Sortable columns arrows are not working in FF

### ISSUE THREAD

**Issue by mmuller** [instedd/planwise#606]
**Found in version** https://github.com/instedd/planwise/commit/bc2bf5ae064ff6d4edfdc892f12a9e363a137b22

**Browser:** Firefox 86.0

**Steps to reproduce:**

1. Navigate to the scenarios list.
2. Sort the list by any column in descending order.
3. Observe the arrow icon.

**Obtained result:**
- The arrow indicates that the list is sorted in ascending order.

**Screenshot:**
![image](https://user-images.githubusercontent.com/518152/111509438-7e76f200-872b-11eb-9940-ab7f8cd7cd50.png)
![image](https://user-images.githubusercontent.com/518152/111510641-bf233b00-872c-11eb-8320-2cd9bf51b259.png)

Besides that, the arrows are always displayed.

**Comment by ismaelbej** [comment]
I'm trying to reproduce on FF 86.0.1 with https://planwise-stg.instedd.org/projects2/269 but the arrows work fine.

**Comment by mmuller** [comment]
I can't reproduce this error anymore
