### ISSUE TITLE
'Target' can be greater than 'Total Facilities'

### ISSUE THREAD

**Issue by mmuller** [instedd/planwise#61]
Found in version 92a3c56

Preconditions:
There are no facilities imported yet

Reproduce steps:
Create a Project
Import a Collection from Resourcemap
Navigate to the Project
Go to the Facilities tab
Check the Facilities types (Hospital and Clinic)

Obtained:
'Target' has a value greater than the 'Total Facilities' value.

Expected:
Target should not be greater than 'Total Facilities'

![screen shot 2016-07-22 at 1 15 39 pm](https://cloud.githubusercontent.com/assets/518152/17063854/c37291e6-500f-11e6-9c16-a48b126b495e.png)

**Comment by ggiraldez** [comment]
Fixed by #75.

**Comment by mmuller** [comment]
Working as expected in version 7202d3e
