### ISSUE TITLE
'Target' value for each Project is not displayed in the Projects listing.

### ISSUE THREAD

**Issue by mmuller** [instedd/planwise#62]
Found in version 92a3c56

Preconditions:
The Project 'Foo' has a value for Target.

Reproduce steps:
Navigate to the Projects listing
Observe the information displayed for the Project 'Foo'

Obtained:
'Target' value for each Project is not displayed in the Projects listing.

Expected:
'Target' value for each Project should be displayed in the Projects listing.

Prototype: https://projects.invisionapp.com/d/main#/console/2626537/59239115/preview

![screen shot 2016-07-22 at 1 33 30 pm](https://cloud.githubusercontent.com/assets/518152/17064070/00ac4754-5011-11e6-8d3b-71cf6c2bce37.png)

**Comment by ggiraldez** [comment]
This actually refers to the target vs total count of facilities, so it is not fixed by #75.

**Comment by mmuller** [comment]
Working as expected in version 7202d3e
