### ISSUE TITLE
Drop-down out of range in providers and consumers

### ISSUE THREAD

**Issue by manumoreira** [instedd/planwise#630]
In consumers and providers screens the drop-downs for data sets are out of vertical range and some options are not shown
![Screen Recording 2021-04-14 at 13 31 18](https://user-images.githubusercontent.com/31930782/114747121-dd2d8c80-9d26-11eb-9a27-ab6171f344dd.gif)

**Comment by manumoreira** [comment]
Quite obvious but adjusting top and bottom margins to css fixes this

**Comment by mmuller** [comment]
Now in version fde618b1 the dropdown is not overlapped with the header, but some options are still hidden, and the dropdown is still out of range.
