### ISSUE TITLE
Add units to actions in map screen

### ISSUE THREAD

**Issue by manumoreira** [instedd/planwise#645]
In the bar at the map screen we should add a detailed text using the Demand, Capacity, Providers units.
New build with `number of capacity-units` `capacity-units` to serve `number of demand-units` `demand-units`
`Cost` (if available)

Increased capacity on `number of capacity units` `capacity-units` to serve `number of demand-units` `demand-units`
`Cost` (if available)

Upgraded and incresed capacity on `number of capacity units` `capacity-units` to serve `number of demand-units` `demand-units`
`Cost` (if available)

![Screen Shot 2021-04-29 at 18 30 15](https://user-images.githubusercontent.com/31930782/116622143-9b056d00-a91a-11eb-9925-2d74808d272c.png)

**Comment by ggiraldez** [comment]
Closing this as it was done in May.
