### ISSUE TITLE
Projects can be created without 'Goal' description

### ISSUE THREAD

**Issue by mmuller** [instedd/planwise#65]
Found in version 92a3c56

Reproduce steps:
Navigate to the Projects listing
Press 'New project'
Don't fill the 'Goal' field but insert one space
Press 'Create' button

Obtained:
In the Projects listing the new Project has no value for the field 'Goal'.

Expected:
Projects should have a description for the Goal field.

![screen shot 2016-07-22 at 5 29 45 pm](https://cloud.githubusercontent.com/assets/518152/17070390/fec70e9e-5031-11e6-8c51-1cbcd31e6763.png)

**Comment by ggiraldez** [comment]
Fixed by 60516d91588e459399551c1f7791c9cb8248ba02

**Comment by mmuller** [comment]
Working as expected in version 7202d3e
