### ISSUE TITLE
Label changes for units

### ISSUE THREAD

**Issue by manumoreira** [instedd/planwise#651]
Labels to change
- Wizard
    - Provider unit ->  Provider units
    - Capacity unit ->  Capacity units
    - Demand unit ->  Demand units
- Increase modal
    - Original capacity [Capacity-unit] ->  Current [Capacity-units]
    - Extra capacity -> [Capacity-units] to add
    - Required capacity -> Required [Capacity-units]
    - Unsatisfied demand -> [Demand-units] without service
- Create modal
    - Capacity [Capacity-units] ->  [Capacity-units]
    - Required capacity -> Required [Capacity-units]
    - Unsatisfied demand -> [Demand-units] without service

**Comment by ggiraldez** [comment]
Closing as this was already implemented back in May.
