### ISSUE TITLE
Specific incons for actions in map

### ISSUE THREAD

**Issue by manumoreira** [instedd/planwise#653]
Currently when suggestions are displayed the icons in the map are simple turquoise squares 
<img width="550" alt="Screen Shot 2021-05-06 at 16 43 00" src="https://user-images.githubusercontent.com/31930782/117356619-56358500-ae8a-11eb-876c-ba54233e99d8.png">
To be consistent with the original design we should use the action icons (Build, increase)
https://projects.invisionapp.com/d/main#/console/13565845/394090846/preview
If we can assign a different class to the icons depending on the action type, then @jkicillof can adjust the design from css.

**Comment by ismaelbej** [comment]
Merged together with PR #655.

**Comment by manumoreira** [comment]
@jkicillof new classes have been added, please include the icons from css

**Comment by ggiraldez** [comment]
This is fixed in https://github.com/instedd/planwise/pull/701
