### ISSUE TITLE
Fix copy for coverage in review screen

### ISSUE THREAD

**Issue by manumoreira** [instedd/planwise#656]
When "Walk distance or Travel by car" is selected in the coverage screen the copy in the review screen is not right. It seems that it only describes the state of the walking coverage method.
<img width="1629" alt="Screen Shot 2021-05-08 at 17 22 08" src="https://user-images.githubusercontent.com/31930782/117553318-3e473800-b027-11eb-8767-bd4f87f652bd.png">
<img width="1629" alt="Screen Shot 2021-05-08 at 17 45 31" src="https://user-images.githubusercontent.com/31930782/117553242-b8c38800-b026-11eb-8d31-853b0f51b689.png">

**Comment by ismaelbej** [comment]
A fix for this behavior was committed with #633.
