### ISSUE TITLE
Suggestions are lost when expanding to table view

### ISSUE THREAD

**Issue by manumoreira** [instedd/planwise#663]
If I get suggestions for new providers or increasing existing providers the list in the bar is lost after expanding it to table view
![suggestionsGone](https://user-images.githubusercontent.com/31930782/119140070-21910400-ba1a-11eb-97b1-5b698274956c.gif)
Maybe the simplest way would be just disabling the expand button when suggestions are shown in the bar

**Comment by ggiraldez** [comment]
I think a more important question is what should be rendered in the expanded view _when the sidebar was listing suggestions_. Right now the table in the expanded view always renders the existing scenario changes, but maybe it makes sense to expand the suggestion data if they were being listed? The [mockup](https://projects.invisionapp.com/d/main?origin=v7#/console/13565845/394090845/preview) does not include the expand button when listing suggestions. That (or disabling the button) are pretty easy to implement. Should I proceed with that option?

**Comment by manumoreira** [comment]
I like the idea of expanding the suggestion list to the table view if we have something else to show, if we will just show the same information in a wider view it doesn't make much sense, I prefer disabling the button.
