### ISSUE TITLE
Search by providers name in the map view

### ISSUE THREAD

**Issue by manumoreira** [instedd/planwise#666]
As a user, I want to be able to search for a specific provider in the map view.
The search can be done by:
- id 
- name

ask @jkicillof a mockup for this

**Comment by jkicillof** [comment]
[Scenario](https://projects.invisionapp.com/d/main#/console/13565845/461195644/preview): Download CSV and Create new scenario from here were moved to the 3 dots menu on the header and everything below the Scenario header on the map side bar should be scrollable. The FAB button could get hidden with a transition if scroll is not 0.
[Search](https://projects.invisionapp.com/d/main#/console/13565845/461195645/preview): The search bar could move to top either on search result or search focus. I think the last option feels more natural.
