### ISSUE TITLE
Add a standard X for the closing list of suggestions instead of the orange FAB

### ISSUE THREAD

**Issue by manumoreira** [instedd/planwise#689]
The suggestion list has a huge orange FAB to close, adding a standard X like in the [mockup](https://projects.invisionapp.com/d/main#/console/13565845/394090845/preview) sounds like a better option 
 
<img width="413" alt="Screen Shot 2021-12-01 at 13 22 52" src="https://user-images.githubusercontent.com/31930782/144272752-e9aeb0e6-2e44-4e4f-aa37-75bb05be7909.png">

**Comment by ggiraldez** [comment]
This will be fixed by my next PR.
