### ISSUE TITLE
Change orange line defining coverage area by a gray dotted line

### ISSUE THREAD

**Issue by manumoreira** [instedd/planwise#690]
Currently, the coverage area is defined with an orange line
![image](https://user-images.githubusercontent.com/31930782/144278890-3b85a3cc-9712-4301-a160-affc5cce669e.png)
This can be consuming as orange is a color of the scale used for sources.
It will be good to change it by a gray dotted line

**Comment by ggiraldez** [comment]
Something like this perhaps? :grin: 

![coverage-polygon](https://user-images.githubusercontent.com/733591/144338285-c3f16965-6cd9-4caf-a78e-f805318a3036.png)

**Comment by manumoreira** [comment]
Looks great to me, @jkicillof do you agree?

**Comment by jkicillof** [comment]
Almost 😬 
Could be a dotted not dashed line? if not could you remove de rounded caps?
