### ISSUE TITLE
Preprocess catchment areas for facilities

### ISSUE THREAD

**Issue by ggiraldez** [instedd/planwise#7]
For each facility, run an algorithm using pgRouting's drivingDistance and PostGIS's ST_Buffer to determine the catchment area for a given threshold. Build the polygons for thresholds ranging from 15 minutes to 6 hours in 5 minutes interval (70 polygons) and save them to the database for later retrieval.

Use `ST_Union(ST_Buffer(edges of drivingDistance))`.

**Comment by nditada** [comment]
I would think that 6 hours is overkill. I would guess than 3 hours is a conservative ceiling. Also, 15 minutes resolution is enough. If there's any performance benefit in reducing the polygon count per facility to 12 instead of 70, don't hesitate changing those parameters.
