### ISSUE TITLE
There is no explicit way to discard project search selection

### ISSUE THREAD

**Issue by pmallol** [instedd/planwise#71]
Found in version a216895

Preconditions:
There are several projects listed, one named 'Kenya'

1. In Projects, click on 'Search projects...'
2. Type letter 'K' and observe how only that project is listed
3. Navigate to Datasets
4. Navigate back to Projects

Obtained:
The 'Search...' component is empty again but the Projects page is still being filtered by letter K. Only by typing again in the search component and erasing what was just written will the list show all projects. 

![screen shot 2016-07-25 at 12 43 30 pm](https://cloud.githubusercontent.com/assets/9214460/17107408/6f35cf0a-5265-11e6-95f9-1703a119fd10.png)

**Comment by mmuller** [comment]
Working as expected in version 7202d3e
