### ISSUE TITLE
Handle the expiration of the JWT token

### ISSUE THREAD

**Issue by ggiraldez** [instedd/planwise#72]
Generated JWT tokens expire after one hour, requiring the user to refresh the page. We have a couple of options here:

- Handle the renewal of the token automatically upon receiving a 401
- Use the session cookie to authenticate API calls (as well as using the JWT token)
- Return a new JWT token on each successful API call (will still expire if not using the app for 1 hour)
- Ask the user to reload the page when receiving a 401

**Comment by ggiraldez** [comment]
Depending on the final solution, it would be desirable to extend the expiration of tokens in development mode.

**Comment by ggiraldez** [comment]
Fixed in #145

**Comment by mmuller** [comment]
Ok in version: v0.4.0-183-g9f0f086
