### ISSUE TITLE
Simplify region shapes in projects

### ISSUE THREAD

**Issue by manumoreira** [instedd/planwise#727]
After using Planwise in several projects it was pretty clear that the quality of the region shapes (polygons) are not aligned with the quality (level of detail) of the population and accessibility (friction) sources. In other words, we have super detailed region shapes combined with more coarse population and friction rasters.

We might consider using the `mapshaper -simplify` command to get a balanced quality of the 3 sources.
Here's an example of size for simplification https://github.com/instedd/planwise/blob/7a102523feca0eb584180a43bc26486205766d0c/scripts/tools/update-region-previews#L59

The main issue with having a highly detailed region shape is that it makes operating with it (eg. for filtering of providers, clipping the demand rasters) very slow while not providing any actual value. 

From the slack conversation

> The most complicated part would be adding a simplification step when importing the regions and choose some criteria for the precision cut.
We have a size criteria implemented [here](https://github.com/instedd/planwise/blob/7a102523feca0eb584180a43bc26486205766d0c/scripts/tools/update-region-previews#L59) which is used for the previews. I would prefer a resolution criteria for this use case, and I'm sure it should be easily doable. Just need to stitch it together.
It may be a good time to migrate the remaining Bash scripts to Babashka. Or at least those involved here: [load-regions](https://github.com/instedd/planwise/blob/7a102523feca0eb584180a43bc26486205766d0c/scripts/population/load-regions) and [load-friction-raster](https://github.com/instedd/planwise/blob/7a102523feca0eb584180a43bc26486205766d0c/scripts/friction/load-friction-raster).

**Comment by manumoreira** [comment]
@ggiraldez please feel free to edit

**Comment by ggiraldez** [comment]
We will want to "pair" this with adding a bit of extra border to the friction rasters (using `-cblend 1` when cutting the regions in the [`load-friction-raster`](https://github.com/instedd/planwise/blob/fba09ef51260f5c7f7edc20c28de4a8ede111ea9/scripts/friction/load-friction-raster) script) which should eliminate issues when there are providers near the limits of the regions and they are inside the region shape but they have no friction data.
