### ISSUE TITLE
Improve outline resolution for smaller regions

### ISSUE THREAD

**Issue by ggiraldez** [instedd/planwise#73]
Use an adaptive simplification coefficient when retrieving the region outlines. We want that coefficient to vary with the size of the bounding box to improve visuals for smaller regions. For example:

![screen shot 2016-07-25 at 15 25 16](https://cloud.githubusercontent.com/assets/733591/17112336/09ce67e6-527c-11e6-881b-4232bbaee5d9.png)

Restrictions:

- Size of transmitted data.
- When asking Mapbox for the static image of the project, that region's GeoJSON must fit in the URL and not exceed Mapbox's limit (otherwise it returns a 422).

See https://github.com/instedd/planwise/blob/78096ec6b70b69e21b3cadf39f3dfbc0371e2652/src/planwise/endpoint/regions.clj#L17

**Comment by mmuller** [comment]
Ok in version v0.4.0-10-g5596157
