### ISSUE TITLE
Projects with several facilities take too much time to response

### ISSUE THREAD

**Issue by mmuller** [instedd/planwise#77]
Preconditions:
The Project 'Foo' has ~15 facilities.

Reproduce steps:
Navigate to the Project 'Foo'
Go to the 'Transport Means' tab
Select '1:45 hours' from the options

Obtained:
The coverage areas are painted after ~10 seconds.

**Comment by ggiraldez** [comment]
This was apparently a transient problem with the network or the haproxy component.

While from the browser, the transfer speed was noticeable slow (in the tens of Kb/s ballpark), from inside the container the response was almost instantaneous. The size of the request is around 300 Kb.

**Comment by mmuller** [comment]
Ok in version v0.4.0-151-gf78af9f
