### ISSUE TITLE
Tweak the simplify parameter when retrieving isochrones

### ISSUE THREAD

**Issue by ggiraldez** [instedd/planwise#78]
If we continue to use vector isochrones (returned as GeoJSON) we'll need to simplify the returned result. Currently, with ~15 facilities and a threshold of 2 hours the resulting request is 370 Kb. This will not scale with a larger number of facilities.

See also #77.

**Comment by ggiraldez** [comment]
Another possible optimization is retrieving only the isochrones in the currently visible viewport. Balance that against the size of the request.

**Comment by spalladino** [comment]
# RFC

Set up a new leaflet module (in plain js) that wraps a FeatureGroup Layer with a bbox strategy. The module should require a function that, given the bounding box, a set of already loaded items, and a promise, realises the promise with the new items loaded for that bounding box. All items should be loaded into a cache to avoid repeating requests.

The behaviour and usage should be as follows:
1- The user pans to a viewport
2- The plugin checks whether the viewport is fully contained within the cached area; if it is, then finishes, if there is part of the viewport outside the cached area, then proceeds
3- The plugin invokes the callback function with the current bounding box plus a margin, and the list of feature IDs that it has already loaded
4- The function fires an AJAX request to the server, specifying the IDs already loaded and the bounding box
5- The server retrieves all features that overlap with such bbox _that are not included in the list of already loaded IDs_ and returns them to the client
6- The client passes the new features on to the layer, which in turn renders them

The module should also accept a low-res default layer, which is displayed on small zoom levels. When the user zooms in to a certain zoom level, then the behaviour described above is triggered. The low-res layer could also be used as a fallback while the high-res layer for a new area is being loaded.

This would imply that we only work with two versions of the layer: 
* A low-res one, retrieved in full when the map loads and used for small zoom levels
* A high-res one, loaded incrementally by viewport, used for high zoom levels

Alternatively, we could use zoom level buckets, having different mid-res layers, though this seems overkill for the moment.

**Comment by spalladino** [comment]
Keeping track of the already cached areas would require a data structure that supports:
1- Adding a new rectangle to it
2- Querying whether a rectangle is contained within the union of all the rectangles in the structure

Any ideas for something off-the-shelf that covers this?

**Comment by spalladino** [comment]
OpenLayers, which has a native bbox loading strategy, seems to rely on [RBush](https://github.com/mourner/rbush) _a high-performance JavaScript R-tree-based 2D spatial index for points and rectangles_, we could use the same.

**Comment by mmuller** [comment]
Ok in version v0.4.0-151-gf78af9f
