### ISSUE TITLE
Projects can be created without region

### ISSUE THREAD

**Issue by mmuller** [instedd/planwise#81]
Reproduce steps:
Navigate to the Project listing
Press 'New Project'
Fill the field 'Goal'
Don't select a value for 'Location'
Press 'Create'

Obtained:
The Project is created without region

Expected:
Projects should be scoped by region

**Comment by ggiraldez** [comment]
Fixed in #85.

**Comment by mmuller** [comment]
Working as expected in version 7202d3e
