### ISSUE TITLE
Number of projects listed line breaks if number is higher than one digit

### ISSUE THREAD

**Issue by pmallol** [instedd/planwise#82]
If there are more than 9 projects being listed the "X projects" description next to the search bar breaks in two lines

![screen shot 2016-07-26 at 2 45 47 pm](https://cloud.githubusercontent.com/assets/9214460/17149175/8ae7c1d2-5340-11e6-8126-812e02b20a7a.png)

**Comment by mmuller** [comment]
Projects total count is displayed as expected in version 7202d3e
