### ISSUE TITLE
Display a message notifying users when the application doesn’t have routing information 

### ISSUE THREAD

**Issue by mmuller** [instedd/planwise#89]
We can display an alert when a user is importing sites outside the area where we have routing information.

We could display something like "warning: there are some sites outside the area where we have routing information"

**Comment by ggiraldez** [comment]
See #101

**Comment by ggiraldez** [comment]
Partially fixed by #170. But we could issue a warning at the beginning/end of the import process if the sites are outside the covered region(s).

**Comment by spalladino** [comment]
Report the following warnings as a result from the import process:
- Number of sites not imported since they don't have location
- Number of sites not processed because they are outside of the regions in the system
- Number of sites not processed because they are too far away from the road network

**Comment by mmuller** [comment]
Ok in version v0.4.0-253-g00446b8
