### ISSUE TITLE
Datasets information is not valid if page refreshed while importing

### ISSUE THREAD

**Issue by ggiraldez** [instedd/planwise#94]
Steps to reproduce:

1. Start an import process
2. Navigate to projects
3. Reload the page
4. Wait for a status tick to request the importer status
5. Navigate back to datasets

Obtained: the page incorrectly shows that the user is not authorized to access Resourcemap.
Expected: the collection list is shown (disabled) along the import status.

This is because the status tick overwrites the `[:datasets :state]` which is initially nil, but not the rest of the information. Then later the client assumes it has already initialized the authorization/collections and doesn't issue the initial request to the datasets endpoint.

**Comment by mmuller** [comment]
Ok in version v0.4.0-151-gf78af9f
